### ISSUE TITLE
Too many open files './models/model_args.json'

### ISSUE THREAD

**Issue by ITworkonline** [ThilinaRajapakse/simpletransformers#1096]
**Describe the bug**
I faced one problem when I want to deploy the model on the server written by flask. I have successfully got the predict result by loading the models and predicting method. But when I try to wrap this function and use it as an api in app.py(flask), it always shows ((((Too many open files './models/model_args.json'))). I have tried to increase the ulimit. It's still not working. Can anyone help with that?

**Comment by ThilinaRajapakse** [comment]
Turning off all the `multiprocessing` related features should solve this.

**Comment by ITworkonline** [comment]
> Turning off all the `multiprocessing` related features should solve this.

I tried with passing args inside ClassificationModel, it's still showing the same error.
`model = ClassificationModel('roberta', './models', use_cuda=False, use_multiprocessing = False)
`
 And here is all my code in main.py for flask. Pretty simple and straightforward.



`
from flask import Flask, request
from flask_restful import Resource, Api

#from prediction_service_model import predict

from simpletransformers.classification import ClassificationModel


app = Flask(__name__)
api = Api(app)

#jie
@app.route('/')
def get():
    return {
        "Test": "Test value"
    }

@app.route('/predict')
def predict_sentence():
    sentence1 = request.args.get('sentence1')
    sentence2 = request.args.get('sentence2')

    model = ClassificationModel('roberta', './models', use_cuda=False, use_multiprocessing = False)

    predictions, raw_outputs = model.predict(
    [
        [
            sentence1,
            sentence2
        ]
    ]
)
    return {
        "sentence1": sentence1,
        "sentence2": sentence2,
        "prediction": predictions,
        # "result": result,
    }


if __name__ == '__main__':
    app.run(host='127.0.0.1', port=8080, debug=True)

`

**Comment by ITworkonline** [comment]
Also, I am trying another way to solve this. Replicating the predict() from the source code. I got this error when I define the model. "torch.nn.modules.module.ModuleAttributeError: 'RobertaForSequenceClassification' object has no attribute 'run'" 

Here is how I define the model (trained)

`MODEL_CLASSES = {"roberta": (RobertaConfig, RobertaForSequenceClassification, RobertaTokenizerFast)}
config_class, model_class, tokenizer_class = MODEL_CLASSES["roberta"]
tokenizer_name = "roberta-base"
tokenizer = tokenizer_class.from_pretrained(
                tokenizer_name, do_lower_case=False)


config = config_class.from_pretrained("roberta-base", num_labels=2)
model = model_class.from_pretrained("roberta-base", `config=config)`

I am not sure if I define it correctly. Can someone help me with that? Thanks a lot!

**Comment by lee-van-oetz** [comment]
I am getting this with being able to have 1021 files open and `use_multiprocessing` set to `False`. Any ideas?
